# Generated by Django 2.2.8 on 2020-01-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0003_auto_20171031_1331"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("github_issue", models.CharField(blank=True, max_length=100)),
                (
                    "gss",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="councils.Council",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_valid", models.BooleanField()),
                ("csv_rows", models.IntegerField(default=0)),
                ("ems", models.CharField(max_length=40)),
                ("key", models.CharField(max_length=255)),
                ("errors", models.TextField(blank=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file_uploads.Upload",
                    ),
                ),
            ],
        ),
    ]
