# Generated by Django 2.2.9 on 2020-02-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_uploads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="upload", options={"get_latest_by": "timestamp"},
        ),
    ]
