# Generated by Django 4.1.5 on 2023-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_uploads", "0004_election_date_on_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="warning_about_pending_sent",
            field=models.BooleanField(default=False),
        ),
    ]
