# Generated by Django 4.1.7 on 2023-03-08 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_uploads", "0005_upload_warning_about_pending_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="upload_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
