# Generated by Django 5.2.15 on 2026-07-24 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councils', '0010_add_council_user_m2m'),
        ('file_uploads', '0006_upload_upload_user'),
        ('pollingstations', '0026_alter_pollingstation_location_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(max_length=255)),
                ('election_title', models.CharField(blank=True, max_length=255)),
                ('poll_open_date', models.DateField()),
                ('requires_voter_id', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='councils.council')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('council', 'election_id')},
            },
        ),
        migrations.CreateModel(
            name='ElectoralDataReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electorate', models.PositiveIntegerField(help_text='Total number of registered electors.')),
                ('postal_electorate', models.PositiveIntegerField(blank=True, help_text='Number of electors registered to vote by post.', null=True)),
                ('postal_votes_issued', models.PositiveIntegerField(blank=True, null=True)),
                ('postal_votes_returned', models.PositiveIntegerField(blank=True, null=True)),
                ('postal_votes_rejected_no_signature', models.PositiveIntegerField(default=0)),
                ('postal_votes_rejected_no_dob', models.PositiveIntegerField(default=0)),
                ('postal_votes_rejected_signature_mismatch', models.PositiveIntegerField(default=0)),
                ('postal_votes_rejected_dob_mismatch', models.PositiveIntegerField(default=0)),
                ('postal_votes_rejected_late', models.PositiveIntegerField(default=0, help_text='Received after close of poll.')),
                ('ballot_papers_issued', models.PositiveIntegerField(blank=True, help_text='Total number of ballot papers issued (turnout).', null=True)),
                ('rejected_ballots_no_official_mark', models.PositiveIntegerField(default=0)),
                ('rejected_ballots_voted_for_too_many', models.PositiveIntegerField(default=0)),
                ('rejected_ballots_identifying_mark', models.PositiveIntegerField(default=0)),
                ('rejected_ballots_unmarked_or_void', models.PositiveIntegerField(default=0)),
                ('election_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_data', to='file_uploads.electionreturn')),
            ],
            options={
                'verbose_name': 'Electoral data return',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_1_summary', models.TextField(blank=True, help_text='Electoral services are robust and support the delivery of well-run elections.', verbose_name='Outcome 1')),
                ('outcome_2_summary', models.TextField(blank=True, help_text='Everybody who is eligible and wants to vote is able to do so and has confidence in the voting process.', verbose_name='Outcome 2')),
                ('outcome_3_summary', models.TextField(blank=True, help_text='Everybody who is eligible and wants to stand for election is able to do so and has confidence in the process.', verbose_name='Outcome 3')),
                ('outcome_4_summary', models.TextField(blank=True, help_text='Everyone can have confidence that the election process is well managed and in the accuracy of the results.', verbose_name='Outcome 4')),
                ('submitted', models.BooleanField(default=False)),
                ('election_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report', to='file_uploads.electionreturn')),
            ],
            options={
                'verbose_name': 'Performance report',
            },
        ),
        migrations.CreateModel(
            name='PollingStationVoterIDReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station_label', models.CharField(blank=True, max_length=255)),
                ('meeter_greeter_employed', models.BooleanField(blank=True, help_text='Was a meeter/greeter employed for most of the day?', null=True)),
                ('vac_used', models.PositiveIntegerField(default=0, verbose_name='1a. Voter Authority Certificates used')),
                ('aed_used', models.PositiveIntegerField(default=0, verbose_name="1b. Anonymous Elector's Documents used")),
                ('privacy_requests', models.PositiveIntegerField(default=0, verbose_name='2. Voters who asked to show ID in private')),
                ('not_issued_ballot_total', models.PositiveIntegerField(default=0, verbose_name='3a. Not issued with a ballot paper')),
                ('not_issued_then_returned', models.PositiveIntegerField(default=0, verbose_name='3b. ...who later returned with accepted ID')),
                ('refused_ballot_total', models.PositiveIntegerField(default=0, verbose_name='4a. Refused a ballot paper (from the BPRL)')),
                ('refused_then_returned', models.PositiveIntegerField(default=0, verbose_name='4b. ...who later returned and were issued one')),
                ('election_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_id_returns', to='file_uploads.electionreturn')),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pollingstations.pollingstation')),
            ],
            options={
                'verbose_name': 'Polling station Voter ID return (VIDEF)',
                'unique_together': {('election_return', 'polling_station')},
            },
        ),
    ]
