# Generated by Django 5.2.15 on 2026-07-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("councils", "0010_add_council_user_m2m"),
        ("file_uploads", "0006_upload_upload_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="FcsCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("token", models.CharField(max_length=255)),
                (
                    "council",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="councils.council",
                    ),
                ),
            ],
        ),
    ]
