import csv
import json
from collections import namedtuple


class CsvHelper:
    """
    Helper class for reading data from CSV files
    """

    def __init__(self, filepath, encoding="utf-8", delimiter=","):
        self.filepath = filepath
        self.encoding = encoding
        self.delimiter = delimiter

    def get_features(self):
        with open(self.filepath, "rt", encoding=self.encoding) as file:
            reader = csv.reader(file, delimiter=self.delimiter)
            header = next(reader)

            # mimic the data structure generated by ffs so existing import
            # scripts don't break

            # fmt: off
            replace = {
                " ": "_",
                "-": "_",
                ".": "_",
                "(": "",
                ")": "",
                "/": "_",
                "\\": "_",
            }
            # fmt: on

            clean = []
            for s in header:
                s = s.strip().lower()
                for k, v in replace.items():
                    s = s.replace(k, v)
                while "__" in s:
                    s = s.replace("__", "_")
                clean.append(s)
            RowKlass = namedtuple("RowKlass", clean)

            data = []
            for row in map(RowKlass._make, reader):
                data.append(row)

        return data


class JsonHelper:
    """
    Helper class for reading data from JSON files
    """

    def __init__(self, filepath):
        self.filepath = filepath

    def get_features(self):
        with open(self.filepath) as features_file:
            return json.load(features_file)


class FileHelperFactory:
    """
    Factory class for creating file helper objects.

    If we add helper classes for more file types,
    add an extra case to create()
    """

    @staticmethod
    def create(filetype, filepath, options):
        if filetype == "json":
            return JsonHelper(filepath)
        if filetype == "csv":
            return CsvHelper(
                filepath, options["csv_encoding"], options["csv_delimiter"]
            )

        raise ValueError("Unexpected file type: %s" % (filetype))
