# Generated by Django 2.2.15 on 2020-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0009_auto_20160616_0921"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataQuality",
        ),
    ]
