# Generated by Django 4.1.5 on 2023-02-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_uploads", "0004_election_date_on_upload"),
        ("data_importers", "0001_data_quality_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataquality",
            name="station_data_file",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="file_uploads.file",
            ),
        ),
    ]
