# Generated by Django 4.2.9 on 2024-02-01 10:58

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("councils", "0010_add_council_user_m2m"),
        ("file_uploads", "0006_upload_upload_user"),
        ("data_importers", "0001_data_quality_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("IMPORT", "Import script run"),
                            ("TEARDOWN", "Council data torn down"),
                        ]
                    ),
                ),
                (
                    "election_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), default=list, size=None
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="councils.council",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file_uploads.upload",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
