# Generated by Django 4.2.13 on 2025-02-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_importers", "0003_dataevent_payload_alter_dataevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("IMPORT", "Import script run"),
                    ("TEARDOWN", "Council data torn down"),
                    ("SET_STATION_VISIBILITY", "Station visibility changed"),
                ],
                max_length=255,
            ),
        ),
    ]
