# Generated by Django 2.2.10 on 2020-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_auto_20171129_1424"),
    ]

    operations = [
        migrations.DeleteModel(name="Feedback",),
    ]
