# Generated by Django 2.2.16 on 2020-12-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_auto_20171129_1424"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"get_latest_by": "modified"},
        ),
    ]
