# Generated by Django 3.2.12 on 2022-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_time_stamped_model_operation_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="vote",
            field=models.CharField(
                blank=True, choices=[("YES", "Yes"), ("NO", "No")], max_length=100
            ),
        ),
    ]
