# Generated by Django 4.2.13 on 2024-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_feedback_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="asana_url",
            field=models.URLField(blank=True),
        ),
    ]
