# Generated by Django 4.2.23 on 2025-08-28 12:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_alter_feedback_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoElectionFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("no_election_feedback_text", models.TextField(blank=True)),
                ("source_url", models.CharField(blank=True, max_length=800)),
                ("token", models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "No Election Page Feedback",
                "verbose_name_plural": "No Election Page Feedback",
            },
        ),
    ]
