#!/bin/sh
#
# This is a script that makes runnning manage.py inside a virtualenv from
# cron easier.
# It does a few things:
#     1. It wraps comands in `output-on-error`
#     2. It calls the manage.py with the virtualenv's python
# It requires the project to be at /var/www/{{ project_name }}
#
output-on-error /var/www/${PROJECT_NAME}/code/.venv/bin/python /var/www/${PROJECT_NAME}/code/manage.py "$@"
