from data_importers.ems_importers import BaseHalaroseCsvImporter

SLK_EXCLUDE_STATIONS = (
    "8-cumbernauld-ps-and-st-andrews-ps",
    "7-cumbernauld-ps-and-st-andrews-ps",
    "7-chapelhall-primary-and-st-aloysius-primary-schools",
    "6-st-brigids-primary-school",
    "6-pat-cullinan-centre",
    "6-noble-primary-school",
    "6-hilltop-primary-school",
    "6-cumbernauld-ps-and-st-andrews-ps",
    "6-chapelhall-primary-and-st-aloysius-primary-schools",
    "6-bellshill-cultural-centre",
    "6-aitkenhead-primary-school",
    "5-wishaw-academy-and-st-ignatius-primary-school",
    "5-st-brigids-primary-school",
    "5-st-aidans-primary-school",
    "5-pat-cullinan-centre",
    "5-noble-primary-school",
    "5-new-stevenston-community-hall",
    "5-muirhouse-primary-school",
    "5-mossend-primary-school",
    "5-lawmuir-primary-school",
    "5-knowetop-primary-school",
    "5-hilltop-primary-school",
    "5-eastfield-primary-school",
    "5-dykehead-primary-school",
    "5-dalziel-high-school",
    "5-cumbernauld-ps-and-st-andrews-ps",
    "5-chapelhall-primary-and-st-aloysius-primary-schools",
    "5-bellshill-cultural-centre",
    "5-all-saints-rochsolloch-primary-schools",
    "5-aitkenhead-primary-school",
    "4-wishaw-academy-and-st-ignatius-primary-school",
    "4-st-michaels-primary-school",
    "4-st-lucys-primary-school",
    "4-st-josephs-primary-school",
    "4-st-helens-primary-school",
    "4-st-brigids-primary-school",
    "4-st-aidans-primary-school",
    "4-pat-cullinan-centre",
    "4-old-monkland-primary-school",
    "4-old-monkland-community-centre",
    "4-noble-primary-school",
    "4-new-stevenston-community-hall",
    "4-muirhouse-primary-school",
    "4-mossend-primary-school",
    "4-lawmuir-primary-school",
    "4-knowetop-primary-school",
    "4-kirkshaws-primary-school",
    "4-kilsyth-primary-school",
    "4-kilsyth-academy",
    "4-kildrum-primary-school",
    "4-john-mccormack-community-centre",
    "4-hilltop-primary-school",
    "4-glencairn-primary-school",
    "4-eastfield-primary-school",
    "4-dykehead-primary-school",
    "4-dalziel-high-school",
    "4-cumbernauld-ps-and-st-andrews-ps",
    "4-cleland-primary-school",
    "4-chapelhall-primary-and-st-aloysius-primary-schools",
    "4-carnbroe-primary-school",
    "4-cambusnethan-primary-school",
    "4-broadwood-stadium",
    "4-bellshill-cultural-centre",
    "4-all-saints-rochsolloch-primary-schools",
    "4-aitkenhead-primary-school",
    "3-woodlands-primary-school",
    "3-wishaw-academy-and-st-ignatius-primary-school",
    "3-whitelees-primary-school",
    "3-victoria-primary-school",
    "3-thornlie-primary-school",
    "3-the-shawhead-centre",
    "3-the-reigart-suite",
    "3-the-chapelside-centre",
    "3-tannochside-primary-school",
    "3-stepps-primary-school",
    "3-stane-primary-school",
    "3-st-michaels-primary-school",
    "3-st-margaret-of-scotland-primary-school",
    "3-st-lucys-primary-school",
    "3-st-josephs-primary-school",
    "3-st-helens-primary-school",
    "3-st-brigids-primary-school",
    "3-st-aidans-primary-school",
    "3-springfield-community-centre",
    "3-plains-and-st-davids-primary-schools",
    "3-pather-community-centre",
    "3-pat-cullinan-centre",
    "3-old-monkland-primary-school",
    "3-old-monkland-community-centre",
    "3-noble-primary-school",
    "3-newarthill-primary-school",
    "3-new-stevenston-community-hall",
    "3-netherton-community-centre",
    "3-muirhouse-primary-school",
    "3-muirfield-centre",
    "3-mossend-primary-school",
    "3-lawmuir-primary-school",
    "3-langloan-primary-school",
    "3-knowetop-primary-school",
    "3-kirkshaws-primary-school",
    "3-kilsyth-primary-school",
    "3-kilsyth-academy",
    "3-kildrum-primary-school",
    "3-keir-hardie-memorial-primary-school",
    "3-john-mccormack-community-centre",
    "3-holytown-primary-school",
    "3-hilltop-primary-school",
    "3-glenmavis-community-centre",
    "3-glenmanor-primary-school",
    "3-glengowan-st-marys-primary-schools",
    "3-glencairn-primary-school",
    "3-gartcosh-hall",
    "3-eastfield-primary-school",
    "3-dykehead-primary-school",
    "3-devonview-pre-school-centre",
    "3-dalziel-high-school",
    "3-cumbernauld-ps-and-st-andrews-ps",
    "3-cleland-primary-school",
    "3-chryston-primary-school",
    "3-chapelhall-primary-and-st-aloysius-primary-schools",
    "3-carnbroe-primary-school",
    "3-cambusnethan-primary-school",
    "3-calderbank-primary-school",
    "3-calder-parish-church-hall",
    "3-burnhead-community-centre",
    "3-broadwood-stadium",
    "3-braidhurst-high-school",
    "3-bellshill-cultural-centre",
    "3-bargeddie-and-st-kevins-primary-schools",
    "3-all-saints-rochsolloch-primary-schools",
    "3-aitkenhead-primary-school",
    "2-woodlands-primary-school",
    "2-wishawhill-community-centre",
    "2-wishaw-academy-and-st-ignatius-primary-school",
    "2-whitelees-primary-school",
    "2-westfield-primary-school",
    "2-victoria-primary-school",
    "2-thornlie-primary-school",
    "2-the-village-community-centre",
    "2-the-shawhead-centre",
    "2-the-reigart-suite",
    "2-the-chapelside-centre",
    "2-tannochside-primary-school",
    "2-stepps-primary-school",
    "2-stane-primary-school",
    "2-st-serfs-primary-school",
    "2-st-patricks-primary-school",
    "2-st-michaels-primary-school",
    "2-st-margaret-of-scotland-primary-school",
    "2-st-lucys-primary-school",
    "2-st-josephs-primary-school",
    "2-st-helens-primary-school",
    "2-st-dominics-primary-school",
    "2-st-brigids-primary-school",
    "2-st-bartholomews-primary-school",
    "2-st-barbaras-primary-school",
    "2-st-augustines-primary-school",
    "2-st-aidans-primary-school",
    "2-springfield-community-centre",
    "2-skills-academy-former-inclusion-support-base",
    "2-sikeside-primary-school",
    "2-salsburgh-community-centre",
    "2-plains-and-st-davids-primary-schools",
    "2-pather-community-centre",
    "2-pat-cullinan-centre",
    "2-overtown-community-centre",
    "2-our-lady-and-st-francis-primary-school",
    "2-old-monkland-primary-school",
    "2-old-monkland-community-centre",
    "2-noble-primary-school",
    "2-newarthill-primary-school",
    "2-new-stevenston-community-hall",
    "2-netherton-community-centre",
    "2-muirhouse-primary-school",
    "2-muirfield-centre",
    "2-muir-street-primary-school",
    "2-mossend-primary-school",
    "2-masonic-hall",
    "2-lawmuir-primary-school",
    "2-langloan-primary-school",
    "2-knowetop-primary-school",
    "2-kirkshaws-primary-school",
    "2-kilsyth-primary-school",
    "2-kilsyth-academy",
    "2-kildrum-primary-school",
    "2-keir-hardie-memorial-primary-school",
    "2-john-paul-ii-primary-school",
    "2-john-mccormack-community-centre",
    "2-jim-foley-community-centre",
    "2-jerviston-community-centre",
    "2-holytown-primary-school",
    "2-holytown-community-education-centre",
    "2-hilltop-primary-school",
    "2-greengairs-primary-school",
    "2-golfhill-primary-school",
    "2-glenmavis-community-centre",
    "2-glenmanor-primary-school",
    "2-glengowan-st-marys-primary-schools",
    "2-glencairn-primary-school",
    "2-glenboig-and-our-lady-and-st-josephs-ps",
    "2-gartlea-community-centre",
    "2-gartcosh-hall",
    "2-fallside-school",
    "2-eastfield-primary-school",
    "2-dykehead-primary-school",
    "2-devonview-pre-school-centre",
    "2-dalziel-high-school",
    "2-daisy-park-community-centre",
    "2-cumbernauld-ps-and-st-andrews-ps",
    "2-condorrat-parish-church-hall",
    "2-community-education-centre",
    "2-cleland-primary-school",
    "2-clarkston-primary-school",
    "2-chryston-primary-school",
    "2-chapelhall-primary-and-st-aloysius-primary-schools",
    "2-carrick-hall",
    "2-carnbroe-primary-school",
    "2-carbrain-primary-school",
    "2-cambusnethan-primary-school",
    "2-calderbank-primary-school",
    "2-calder-parish-church-hall",
    "2-burnhead-community-centre",
    "2-burngreen-hall",
    "2-broadwood-stadium",
    "2-braidhurst-high-school",
    "2-berryhill-primary-school",
    "2-bellshill-cultural-centre",
    "2-bargeddie-and-st-kevins-primary-schools",
    "2-allanton-primary-school",
    "2-all-saints-rochsolloch-primary-schools",
    "2-aitkenhead-primary-school",
    "2-airdrie-academy",
    "2-abronhill-primary-school",
    "1-woodlands-primary-school",
    "1-wishawhill-community-centre",
    "1-wishaw-academy-and-st-ignatius-primary-school",
    "1-whitelees-primary-school",
    "1-westfield-primary-school",
    "1-waterloo-memorial-hall",
    "1-village-hall",
    "1-victoria-primary-school",
    "1-townhead-primary-school",
    "1-thornlie-primary-school",
    "1-the-village-community-centre",
    "1-the-shawhead-centre",
    "1-the-reigart-suite",
    "1-the-chapelside-centre",
    "1-tannochside-primary-school",
    "1-stepps-primary-school",
    "1-stepping-stones-family-learning-centre",
    "1-stane-primary-school",
    "1-st-serfs-primary-school",
    "1-st-patricks-primary-school",
    "1-st-michaels-primary-school",
    "1-st-margaret-of-scotland-primary-school",
    "1-st-lucys-primary-school",
    "1-st-josephs-primary-school",
    "1-st-helens-primary-school",
    "1-st-dominics-primary-school",
    "1-st-brigids-primary-school",
    "1-st-bartholomews-primary-school",
    "1-st-barbaras-primary-school",
    "1-st-augustines-primary-school",
    "1-st-andrews-primary-school",
    "1-st-aidans-primary-school",
    "1-springfield-community-centre",
    "1-skills-academy-former-inclusion-support-base",
    "1-sikeside-primary-school",
    "1-salsburgh-community-centre",
    "1-ravenswood-primary-school",
    "1-plains-and-st-davids-primary-schools",
    "1-pather-community-centre",
    "1-pat-cullinan-centre",
    "1-overtown-community-centre",
    "1-our-lady-and-st-francis-primary-school",
    "1-old-monkland-primary-school",
    "1-old-monkland-community-centre",
    "1-noble-primary-school",
    "1-newarthill-primary-school",
    "1-new-stevenston-community-hall",
    "1-netherton-community-centre",
    "1-muirhouse-primary-school",
    "1-muirfield-centre",
    "1-muir-street-primary-school",
    "1-mossend-primary-school",
    "1-morningside-primary-school",
    "1-masonic-hall",
    "1-lawmuir-primary-school",
    "1-langloan-primary-school",
    "1-knowetop-primary-school",
    "1-kirkshaws-primary-school",
    "1-kilsyth-primary-school",
    "1-kilsyth-academy",
    "1-kildrum-primary-school",
    "1-keir-hardie-memorial-primary-school",
    "1-john-paul-ii-primary-school",
    "1-john-mccormack-community-centre",
    "1-jim-foley-community-centre",
    "1-jerviston-community-centre",
    "1-holytown-primary-school",
    "1-holytown-community-education-centre",
    "1-holy-trinity-and-all-saints-church-hall",
    "1-holy-cross-primary-school",
    "1-hilltop-primary-school",
    "1-greenhill-primary-school",
    "1-greengairs-primary-school",
    "1-gowkthrapple-community-centre",
    "1-golfhill-primary-school",
    "1-glenmavis-community-centre",
    "1-glenmanor-primary-school",
    "1-glengowan-st-marys-primary-schools",
    "1-glencairn-primary-school",
    "1-glenboig-and-our-lady-and-st-josephs-ps",
    "1-gartlea-community-centre",
    "1-gartcosh-hall",
    "1-fallside-school",
    "1-eastfield-primary-school",
    "1-dykehead-primary-school",
    "1-dunbeth-nursery-centre",
    "1-devonview-pre-school-centre",
    "1-dalziel-high-school",
    "1-daisy-park-community-centre",
    "1-cumbernauld-ps-and-st-andrews-ps",
    "1-condorrat-primary-school",
    "1-condorrat-parish-church-hall",
    "1-community-education-centre",
    "1-coatdyke-congregational-church",
    "1-cleland-primary-school",
    "1-clarkston-primary-school",
    "1-chryston-primary-school",
    "1-chapelhall-primary-and-st-aloysius-primary-schools",
    "1-chapelgreen-primary-school",
    "1-carrick-hall",
    "1-carnbroe-primary-school",
    "1-carbrain-primary-school",
    "1-cambusnethan-primary-school",
    "1-calderbank-primary-school",
    "1-calder-parish-church-hall",
    "1-burnhead-community-centre",
    "1-burngreen-hall",
    "1-broadwood-stadium",
    "1-braidhurst-high-school",
    "1-bonkle-church-hall",
    "1-berryhill-primary-school",
    "1-benhar-evangelical-church",
    "1-bellshill-cultural-centre",
    "1-beechbank-community-centre",
    "1-bargeddie-and-st-kevins-primary-schools",
    "1-banton-primary-school",
    "1-auchinloch-primary-school",
    "1-allanton-primary-school",
    "1-all-saints-rochsolloch-primary-schools",
    "1-aitkenhead-primary-school",
    "1-airdrie-academy",
    "1-ailsa-nursery-centre",
    "1-abronhill-primary-school",
    "1-st-marys-primary-school",
    "2-st-marys-primary-school",
    "3-st-marys-primary-school",
)


def fix_station_hashes(record):
    # These fixes are to ensure station hash is unique
    if (
        record.pollingstationname == "St Mary's Primary School"
        and record.pollingstationaddress_1 == "Cadzow Street"
    ):
        record = record._replace(
            pollingstationname="St Mary's Primary School, Hamilton"
        )

    return record


class Command(BaseHalaroseCsvImporter):
    council_id = "SLK"
    addresses_name = "2021-04-06T11:58:50.790577/North and South Lanarkshire polling_station_export-2021-04-02.csv"
    stations_name = "2021-04-06T11:58:50.790577/North and South Lanarkshire polling_station_export-2021-04-02.csv"
    elections = ["2021-05-06"]

    def address_record_to_dict(self, record):
        record = fix_station_hashes(record)
        station_hash = self.get_station_hash(record)
        if station_hash in SLK_EXCLUDE_STATIONS:
            return None
        if record.housepostcode in [
            "ML11 9BX",
            "ML11 0BG",
            "ML12 6SW",
            "ML11 8PB",
            "ML11 9TS",
            "ML11 0PG",
            "ML8 5LG",
            "G75 8JW",
            "G74 4DF",
            "ML10 6FB",
            "ML10 6ET",
            "G75 8ND",
            "ML10 6PS",
            "G72 8PD",
            "G71 7TD",
            "ML3 6UG",
            "ML3 7UU",
            "ML3 7TF",
            "ML3 7QW",
            "G73 4AP",
            "G72 7XQ",
            "G72 8WN",
            "G74 3ZD",
            "G72 8FG",
        ]:
            return None
        if record.uprn in ["484184237", "484184251"]:
            return None
        return super().address_record_to_dict(record)

    def station_record_to_dict(self, record):

        record = fix_station_hashes(record)
        station_hash = self.get_station_hash(record)

        if station_hash in SLK_EXCLUDE_STATIONS:
            return None

        return super().station_record_to_dict(record)
