from data_importers.ems_importers import BaseDemocracyCountsCsvImporter

RFW_STATIONCODES = (
    "BARGAR_2",
    "BSCOUT_2",
    "STMAGS_2",
    "KIRKCC_2",
    "NEWMAIN_2",
    "LINWOODHS_4",
    "GALLWCC_2",
    "TWEED_1",
    "LINWOODHS_1",
    "STDAVID_1",
    "RENTH_2",
    "TWEED_2",
    "TODPS_4",
    "HOUSTKK_2",
    "SPATESB_1",
    "BEECH_3",
    "ANDREW_2",
    "HOUSTKK_6",
    "JHCPH_2",
    "ERSKINEBC_1",
    "BEECH_1",
    "HUNTER_1",
    "RSPORT_1",
    "WALLACE_5",
    "TODPS_2",
    "TANNAHILL_1",
    "RCC_1",
    "CHARLES_1",
    "WALLACE_2",
    "INCHPC_1",
    "WILLIAM_4",
    "FOXC_2",
    "RSPORT_2",
    "RENFREWSH_2",
    "BREDIPS_2",
    "BROOKVH_1",
    "CHARLES_2",
    "CARGIL_2",
    "RENTH_5",
    "WILLIAM_3",
    "GLYNHIL_1",
    "TANNAHILL_3",
    "THORNPS_1",
    "STJAMES_4",
    "CARGIL_4",
    "RCC_2",
    "GLYNHIL_2",
    "GRC_1",
    "CARGIL_3",
    "CARGIL_1",
    "TWEED_4",
    "BUSHES_2",
    "SPATESB_2",
    "TANNAHILL_5A",
    "STJAMES_2",
    "HOWVH_1",
    "WILLIAM_2",
    "STCATH_3",
    "BREDIPS_3",
    "WILLIAM_6",
    "BISHCC_5",
    "WILLIAM_9",
    "RENFREWSH_3",
    "LCS_2",
    "RENTH_6",
    "BROOKVH_3A",
    "KILSH_3",
    "BREDCC_2",
    "STCATH_1",
    "KILSH_4",
    "BISHCC_4",
    "STANNE_5",
    "HOUSTKK_1",
    "LCS_3",
    "RENFREWSH_1",
    "GLENCC_1",
    "TODPS_1",
    "HERIOT_2",
    "ARKPS_1",
    "CHARLES_3",
    "NEWMAIN_1",
    "TANNAHILL_4",
    "STMARYS_3",
    "BARGAR_5",
    "BSCOUT_4",
    "BARGAR_1",
    "BROOKVH_2A",
    "MARTYRS_2",
    "STMARYS_1",
    "AUCHLOD_3",
    "RIVERCC_2",
    "STANNE_3",
    "LINWOODHS_2",
    "GALLWCC_1",
    "ARKPS_2",
    "LINWOODHS_5A",
    "MCKILIN_3",
    "STCHPS_1",
    "HOWVH_2",
    "WALLACE_4",
    "HUNTER_2",
    "PAISMAR_1",
    "THORNPS_3",
    "WALLACE_1",
    "COCHRAN_1",
    "LANCRGS_1",
    "LANCRGS_2",
    "BUSHES_3",
    "STCATH_2",
    "GLENCC_2",
    "BARGAR_3",
    "MCMAST_2",
    "BISHCC_3",
    "BREDCC_1",
    "WILLIAM_8",
    "HOUSTKK_3",
    "MCMAST_3",
    "FORDB_1",
    "BISHCC_1",
    "JOHNSCC_1",
    "INCHPC_2",
    "RENFREWSH_4",
    "LANCRGS_3",
    "STANNE_4",
    "CARGIL_5A",
    "WILLIAM_1",
    "RENTH_1",
    "ANDREW_1",
    "BREDIPS_4",
    "STJAMES_1",
    "BARGAR_4",
    "STCHPS_2",
    "LCS_1",
    "RENTH_4",
    "FOXC_1",
    "KILSH_1",
    "TODPS_3",
    "DRC_2",
    "GRC_2",
    "DRC_1",
    "WECC_1",
    "BSCOUT_1",
    "HERIOT_1",
    "BEECH_1A",
    "STDAVID_2",
    "ERSKINEBC_3",
    "MARTYRS_1",
    "RIVERCC_1",
    "CHARLES_4",
    "STMARYS_2",
    "BUSHES_1",
    "RENTH_3",
    "HOUSTKK_4",
    "MCMAST_1",
    "KIRKCC_1",
    "LANGVC_1",
    "WILLIAM_7A",
    "STANNE_2",
    "LINWOODHS_3",
    "ERSKINEBC_2",
    "STMAGS_1",
    "WILLIAM_5",
    "JHCPH_1",
    "TANNAHILL_2",
    "TWEED_3",
    "THORNPS_2",
    "STJAMES_3",
    "KILSH_2",
    "HOUSTKK_5",
    "MARTYRS_3",
    "AUCHLOD_2",
    "MCKILIN_2",
    "PAISMAR_2",
    "BREDIPS_1",
    "BISHCC_2",
    "BSCOUT_3",
    "BEECH_2",
    "WALLACE_3",
    "MCKILIN_1",
    "STANNE_1",
    "BISHCC_6A",
)


class Command(BaseDemocracyCountsCsvImporter):
    council_id = "RFW"
    addresses_name = (
        "2021-03-25T10:47:18.268998/Refrew DemocracyClub_PollingDistricts.csv"
    )
    stations_name = (
        "2021-03-25T10:47:18.268998/Refrew DEmocracyClub_PollingStations.csv"
    )
    elections = ["2021-05-06"]

    def address_record_to_dict(self, record):
        if record.stationcode not in RFW_STATIONCODES:
            return None
        return super().address_record_to_dict(record)

    def station_record_to_dict(self, record):
        if record.stationcode not in RFW_STATIONCODES:
            return None
        return super().station_record_to_dict(record)
