# Generated by Django 2.2.9 on 2020-02-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("councils", "0003_auto_20171031_1331"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="council",
            options={"ordering": ("name",)},
        ),
    ]
