# Generated by Django 2.2.17 on 2021-02-01 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("councils", "0006_ec_api_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="council",
            name="area",
        ),
        migrations.CreateModel(
            name="CouncilGeography",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gss", models.CharField(blank=True, max_length=20)),
                (
                    "geography",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "council",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geography",
                        to="councils.Council",
                    ),
                ),
            ],
        ),
    ]
