# Generated by Django 2.2.19 on 2021-03-10 20:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("councils", "0007_add_council_geography_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="name_translated",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
