# Generated by Django 3.2 on 2021-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("councils", "0008_council_name_translated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="council",
            name="name_translated",
            field=models.JSONField(default=dict),
        ),
    ]
