# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 11:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pollingstations", "0013_customfinders")]

    operations = [
        migrations.AddField(
            model_name="residentialaddress",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="residentialaddress",
            name="uprn",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
