# Generated by Django 2.2.16 on 2020-11-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pollingstations", "0014_auto_20180314_1100"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResidentialAddress",
        ),
    ]
