# Generated by Django 3.2.12 on 2022-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0016_advancevotingstation"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancevotingstation",
            name="opening_times",
            field=models.JSONField(null=True),
        ),
    ]
