# Generated by Django 3.2.12 on 2022-04-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("councils", "0010_add_council_user_m2m"),
        ("pollingstations", "0017_advancevotingstation_opening_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancevotingstation",
            name="council",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="councils.council",
            ),
        ),
    ]
