# Generated by Django 4.2.10 on 2024-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0018_advancevotingstation_council"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingstation",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("UNPUBLISHED", "Unpublished")],
                default="PUBLISHED",
            ),
        ),
    ]
