# Generated by Django 4.2.10 on 2024-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0019_pollingstation_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingstation",
            name="internal_council_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="An id used by the council that is not persistent between elections",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="pollingstation",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("UNPUBLISHED", "Unpublished")],
                default="PUBLISHED",
                help_text="\n            Determines visibility level of a station.<br>\n            Whatever this value is set to will persist when an import script is rerun, as long as there isn't a new file\n            from the council.<br>\n            If there has been a new file, then all stations in that file will default to 'published'.<br>\n            This means you need to remember if you want a station to be republished or stay unpublished.\n        ",
            ),
        ),
    ]
