# Generated by Django 4.2.10 on 2024-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0021_accessibilityinformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibilityinformation",
            name="at_the_station_cy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessibilityinformation",
            name="getting_to_the_station_cy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
