# Generated by Django 4.2.13 on 2025-01-23 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0022_accessibilityinformation_at_the_station_cy_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomFinder",
        ),
    ]
