# Generated by Django 5.2.7 on 2025-10-09 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0023_delete_customfinder"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pollingstation",
            new_name="pollingstat_council_b72176_idx",
            old_fields=("council", "internal_council_id"),
        ),
        migrations.RenameIndex(
            model_name="pollingstation",
            new_name="pollingstat_council_19de6a_idx",
            old_fields=("council", "polling_district_id"),
        ),
    ]
