# Generated by Django 5.2.13 on 2026-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pollingstations",
            "0024_rename_pollingstation_council_internal_council_id_pollingstat_council_b72176_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingstation",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("POSTCODE", "Postcode"),
                    ("UPRN", "UPRN"),
                    ("COORDINATES", "Coordinates"),
                ],
                default="",
            ),
        ),
    ]
