# Generated by Django 5.2.13 on 2026-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pollingstations",
            "0024_rename_pollingstation_council_internal_council_id_pollingstat_council_b72176_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingstation",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Published"),
                    ("LOCATION_HIDDEN", "Location hidden"),
                    ("UNPUBLISHED", "Unpublished"),
                ],
                default="PUBLISHED",
                help_text="\n            Determines visibility level of a station.<br>\n            Whatever this value is set to will persist when an import script is rerun, as long as there isn't a new file\n            from the council.<br>\n            If there has been a new file, then all stations in that file will default to 'published'.<br>\n            This means you need to remember if you want a station to be republished or stay unpublished.\n        ",
            ),
        ),
    ]
