# Generated by Django 5.2.13 on 2026-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollingstations", "0025_pollingstation_location_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingstation",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("POSTCODE", "Postcode"),
                    ("UPRN", "UPRN"),
                    ("COORDINATES", "Coordinates"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
