# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbase', '0008_auto_20180102_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsud',
            name='ced',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
