# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("addressbase", "0009_onsud_ced")]

    operations = [migrations.RemoveField(model_name="onsud", name="ctry_flag")]
