# Generated by Django 2.2.10 on 2020-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbase", "0010_remove_onsud_ctry_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="addressbase_postal",
            field=models.CharField(default="D", max_length=1),
            preserve_default=False,
        ),
    ]
