# Generated by Django 2.2.10 on 2020-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbase", "0011_address_addressbase_postal"),
    ]

    operations = [
        migrations.CreateModel(
            name="UprnToCouncil",
            fields=[
                (
                    "uprn",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("lad", models.CharField(blank=True, max_length=9)),
            ],
        ),
        migrations.AddIndex(
            model_name="uprntocouncil",
            index=models.Index(fields=["lad"], name="lookup_lad_idx"),
        ),
    ]
