# Generated by Django 2.2.11 on 2020-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addressbase", "0013_drop_onsud"),
    ]

    operations = [
        migrations.AddField(
            model_name="uprntocouncil",
            name="polling_station_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
