# Generated by Django 4.1.3 on 2023-02-10 10:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("addressbase", "0018_alter_uprntocouncil_advance_voting_station"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uprntocouncil",
            name="lookup_lad_idx",
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["uprn"],
                name="address_uprn_like_idx",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["postcode"], name="address_postcode_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["postcode"],
                name="address_postcode_like_idx",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="address_location_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="uprntocouncil",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["lad"], name="uprntocouncil_lad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uprntocouncil",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["uprn"],
                name="uprntocouncil_uprn_like_idx",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="uprntocouncil",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["advance_voting_station"],
                name="uprntocouncil_adv_v_station_idx",
            ),
        ),
        migrations.RunSQL(
            [("DROP INDEX addressbase_address_location_b1fea538_id;")],
            [
                (
                    "CREATE INDEX addressbase_address_location_b1fea538_id ON addressbase_address USING gist(location);"
                )
            ],
        ),
        migrations.RunSQL(
            [("DROP INDEX addressbase_address_postcode_e4d0a0bc;")],
            [
                (
                    "CREATE INDEX addressbase_address_postcode_e4d0a0bc ON addressbase_address USING btree(postcode);"
                )
            ],
        ),
        migrations.RunSQL(
            [("DROP INDEX addressbase_address_postcode_e4d0a0bc_like;")],
            [
                (
                    "CREATE INDEX addressbase_address_postcode_e4d0a0bc_like ON addressbase_address USING btree(postcode varchar_pattern_ops);"
                )
            ],
        ),
        migrations.RunSQL(
            [("DROP INDEX addressbase_address_uprn_c43af01b_like;")],
            [
                (
                    "CREATE INDEX addressbase_address_uprn_c43af01b_like ON addressbase_address USING btree(uprn varchar_pattern_ops);"
                )
            ],
        ),
        migrations.RunSQL(
            [
                (
                    "DROP INDEX addressbase_uprntocouncil_advance_voting_station_id_770ab03a;"
                )
            ],
            [
                (
                    "CREATE INDEX addressbase_uprntocouncil_advance_voting_station_id_770ab03a ON addressbase_uprntocouncil USING btree(advance_voting_station_id);"
                )
            ],
        ),
        migrations.RunSQL(
            [("DROP INDEX addressbase_uprntocouncil_uprn_7abf1568_like;")],
            [
                (
                    "CREATE INDEX addressbase_uprntocouncil_uprn_7abf1568_like ON addressbase_uprntocouncil USING btree(uprn varchar_pattern_ops);"
                )
            ],
        ),
    ]
