# Generated by Django 5.2.12 on 2026-03-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressbase", "0019_addressbase_named_index"),
        (
            "pollingstations",
            "0024_rename_pollingstation_council_internal_council_id_pollingstat_council_b72176_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uprntocouncil",
            name="uprntocouncil_adv_v_station_idx",
        ),
        migrations.RemoveField(
            model_name="uprntocouncil",
            name="advance_voting_station",
        ),
        migrations.AddField(
            model_name="uprntocouncil",
            name="advance_voting_stations",
            field=models.ManyToManyField(to="pollingstations.advancevotingstation"),
        ),
    ]
