# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 15:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("data_finder", "0008_auto_20170911_1034")]

    operations = [
        migrations.AlterField(
            model_name="loggedpostcode",
            name="council",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="councils.Council",
            ),
        )
    ]
