# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data_finder", "0009_auto_20190108_1533")]

    operations = [
        migrations.AddField(
            model_name="loggedpostcode",
            name="has_election",
            field=models.NullBooleanField(),
        )
    ]
