# Generated by Django 2.2.16 on 2020-12-08 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_finder", "0010_loggedpostcode_has_election"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggedpostcode",
            options={"get_latest_by": "modified"},
        ),
    ]
