# Generated by Django 2.2.19 on 2021-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_finder", "0011_time_stamped_model_operation_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggedpostcode",
            name="referer",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
