# Generated by Django 2.2.19 on 2021-05-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_finder", "0012_log_referer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedpostcode",
            name="referer",
            field=models.CharField(
                blank=True, db_index=True, max_length=800, null=True
            ),
        ),
    ]
