# Generated by Django 4.2 on 2023-11-17 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_finder", "0014_alter_loggedpostcode_has_election"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoggedPostcode",
        ),
    ]
